# dbt project configuration
name: 'weather_bike_demo'
version: '1.0.0'
config-version: 2

profile: 'weather_bike_demo'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  weather_bike_demo:
    staging:
      +materialized: view
      +schema: staging
    core:
      +materialized: table
      +schema: core
    marts:
      +materialized: table
      +schema: marts

vars:
  bike_start_month: "2024-05"
  bike_end_month: "2024-06"
  weather_start_date: "2024-05-01"
  weather_end_date: "2024-06-30"

