weather_bike_demo:
  outputs:
    dev:
      type: duckdb
      path: ../duckdb/warehouse.duckdb
      threads: 4
      extensions:
        - httpfs
        - parquet
      # Attach external DuckDB databases for raw data sources
      attach:
        - path: ../duckdb/bike_ingestion.duckdb
          alias: bike_ingestion
          read_only: true
        - path: ../duckdb/weather_ingestion.duckdb
          alias: weather_ingestion
          read_only: true
        - path: ../duckdb/holiday_ingestion.duckdb
          alias: holiday_ingestion
          read_only: true
    
    prod:
      type: duckdb
      path: ../duckdb/warehouse.duckdb
      threads: 8
      extensions:
        - httpfs
        - parquet
      # Attach external DuckDB databases for raw data sources
      attach:
        - path: ../duckdb/bike_ingestion.duckdb
          alias: bike_ingestion
          read_only: true
        - path: ../duckdb/weather_ingestion.duckdb
          alias: weather_ingestion
          read_only: true
        - path: ../duckdb/holiday_ingestion.duckdb
          alias: holiday_ingestion
          read_only: true
  
  target: dev

