version: 2

models:
  - name: mart_demand_daily
    description: Daily bike demand metrics for business analytics
    columns:
      - name: ride_date
        description: Date of observation
        tests:
          - unique
          - not_null

      - name: trips_total
        description: Total number of trips
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: '> 0'

      - name: member_trips
        description: Number of member trips
        tests:
          - not_null

      - name: casual_trips
        description: Number of casual trips
        tests:
          - not_null

      - name: day_type
        description: Weekday or Weekend
        tests:
          - accepted_values:
              values:
                - Weekday
                - Weekend

  - name: mart_weather_effect
    description: Bike demand enriched with weather data for impact analysis
    columns:
      - name: date
        description: Date of observation
        tests:
          - unique
          - not_null

      - name: trips_total
        description: Total number of trips
        tests:
          - not_null

      - name: temp_category
        description: Categorized temperature range
        tests:
          - accepted_values:
              values:
                - Very Cold
                - Cold
                - Moderate
                - Warm
              config:
                severity: warn

      - name: rain_category
        description: Categorized precipitation level
        tests:
          - accepted_values:
              values:
                - No Rain
                - Light Rain
                - Heavy Rain
              config:
                severity: warn

  - name: mart_station_stats
    description: Station-level statistics for trip analytics and popular station
      identification
    columns:
      - name: station_id
        description: Unique station identifier
        tests:
          - unique
          - not_null

      - name: station_name
        description: Name of the station
        tests:
          - not_null

      - name: start_trip_count
        description: Number of trips starting from this station
        tests:
          - not_null

      - name: end_trip_count
        description: Number of trips ending at this station
        tests:
          - not_null

      - name: total_trip_count
        description: Total trips (starts + ends) for this station
        tests:
          - not_null

      - name: avg_start_duration
        description: Average duration of trips starting from this station

      - name: member_start_trips
        description: Number of member trips starting from this station
        tests:
          - not_null

      - name: casual_start_trips
        description: Number of casual trips starting from this station
        tests:
          - not_null

      - name: member_pct
        description: Percentage of member trips starting from this station

  - name: mart_holiday_analysis
    description: Daily bike demand enriched with holiday data for impact analysis
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('mart_demand_daily')
    columns:
      - name: ride_date
        description: Date of observation
        tests:
          - unique
          - not_null

      - name: is_holiday
        description: Boolean flag indicating if the date is a holiday
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

      - name: holiday_name
        description: Name of the holiday (NULL for non-holidays)

      - name: holiday_category
        description: Categorized holiday type (Federal Holiday, NY State Observance, or NULL)
        tests:
          - accepted_values:
              values:
                - Federal Holiday
                - NY State Observance
              config:
                severity: warn
                where: "holiday_category IS NOT NULL"

      - name: trips_total
        description: Total number of trips on this date
        tests:
          - not_null

      - name: tmax
        description: Maximum temperature in Celsius

      - name: precip
        description: Precipitation sum in mm

      - name: day_type
        description: Weekday or Weekend classification
        tests:
          - accepted_values:
              values:
                - Weekday
                - Weekend

      - name: baseline_daily_trips
        description: Average trips on non-holiday days (baseline for comparison)
        tests:
          - not_null

      - name: demand_vs_baseline_pct
        description: Percentage difference from baseline demand
        tests:
          - dbt_utils.accepted_range:
              min_value: -100
              max_value: 500
              config:
                severity: warn

      - name: trips_weather_adjusted
        description: Weather-adjusted trip count normalized to baseline conditions (20.3°C, 3.1mm precip). Uses 1.5% adjustment per degree C from baseline and logarithmic decay for precipitation (3% per mm with diminishing returns). Capped at 4x adjustment to avoid extreme values.