version: 2

sources:
  - name: raw_holidays
    description: "Raw holiday data ingested from Nager.Date API"
    schema: raw_holidays
    tables:
      - name: us_holidays
        description: "US public holidays with intelligent date deduplication"
        columns:
          - name: date
            description: "Holiday date (primary key)"
            tests:
              - unique
              - not_null
          - name: holiday_name
            description: "Holiday name (concatenated with 'and' for same-date holidays)"
          - name: country_code
            description: "Country code (US)"
          - name: holiday_types
            description: "Comma-separated list of holiday types (Public, Federal, etc.)"

  - name: raw_games
    description: "Raw MLB game data ingested from MLB Stats API"
    schema: raw_games
    tables:
      - name: mlb_games
        description: "NY Yankees and NY Mets home game schedules"
        columns:
          - name: game_id
            description: "Unique game identifier (MLB gamePk)"
          - name: game_date
            description: "Game date (YYYY-MM-DD)"
          - name: game_datetime
            description: "Game start datetime (UTC)"
          - name: venue_name
            description: "Stadium name"

models:
  - name: stg_bike_trips
    description: "Cleaned and normalized bike trip data from raw ingestion"
    columns:
      - name: ride_id
        description: "Unique identifier for each trip"
        tests:
          - unique
          - not_null
      
      - name: started_at
        description: "Trip start timestamp"
        tests:
          - not_null
      
      - name: ended_at
        description: "Trip end timestamp"
        tests:
          - not_null
      
      - name: ride_date
        description: "Date of the trip (truncated from started_at)"
        tests:
          - not_null
      
      - name: ride_mins
        description: "Duration of the trip in minutes"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 720
      
      - name: member_casual
        description: "Type of rider: member or casual"
        tests:
          - accepted_values:
              values: ['member', 'casual']

  - name: stg_weather
    description: |
      Cleaned weather data from Open-Meteo API.
      
      Note: This model preserves records with partial temperature data (NULL tmax or tmin)
      to retain valuable precipitation and wind observations. The tmax >= tmin constraint
      is only enforced when both temperature values are present.
    columns:
      - name: date
        description: "Date of weather observation"
        tests:
          - unique
          - not_null
      
      - name: tmax
        description: "Maximum temperature in Celsius (may be NULL for some records)"
      
      - name: tmin
        description: "Minimum temperature in Celsius (may be NULL for some records)"
      
      - name: precip
        description: "Precipitation sum in mm"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: wind_max
        description: "Maximum wind speed in km/h"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

  - name: stg_holidays
    description: "Cleaned and enriched US holiday data from Nager.Date API with derived flags"
    columns:
      - name: date
        description: "Holiday date (unique per day)"
        tests:
          - unique
          - not_null

      - name: holiday_name
        description: "Holiday name (may contain multiple names joined with 'and' for same-date holidays)"
        tests:
          - not_null

      - name: country_code
        description: "Country code (always US)"
        tests:
          - accepted_values:
              values: ['US']

      - name: is_major
        description: "Whether this is a major holiday (Public or Federal type)"
        tests:
          - not_null

      - name: is_working_day
        description: "Whether this is a working day (inverse of is_major)"
        tests:
          - not_null

      - name: holiday_types
        description: "Comma-separated list of holiday types (Public, Federal, Optional, etc.)"

  - name: stg_games
    description: "Cleaned and enriched MLB game data for NY Yankees and NY Mets home games"
    columns:
      - name: game_id
        description: "Unique game identifier (MLB gamePk)"
        tests:
          - unique
          - not_null

      - name: game_date
        description: "Game date (date type)"
        tests:
          - not_null

      - name: game_datetime
        description: "Game start datetime (timestamp type)"
        tests:
          - not_null

      - name: stadium_name
        description: "Standardized stadium name"
        tests:
          - not_null
          - accepted_values:
              values: ['Yankee Stadium', 'Citi Field']

      - name: is_yankees_home
        description: "Boolean flag for Yankees home games"
        tests:
          - not_null

      - name: is_mets_home
        description: "Boolean flag for Mets home games"
        tests:
          - not_null

      - name: estimated_end_datetime
        description: "Estimated game end time (game_datetime + 3 hours)"
        tests:
          - not_null
