version: 2

sources:
  - name: raw_bike
    description: "Raw bike trip data ingested via dlt pipeline"
    database: bike_ingestion
    schema: raw_bike
    tables:
      - name: bike_trips
        description: "Raw bike trip records from Citi Bike system"
        columns:
          - name: ride_id
            description: "Unique identifier for each trip"
            tests:
              - unique
              - not_null
          
          - name: rideable_type
            description: "Type of bike used (electric_bike, classic_bike, etc.)"
          
          - name: started_at
            description: "Trip start timestamp with timezone"
          
          - name: ended_at
            description: "Trip end timestamp with timezone"
          
          - name: start_station_name
            description: "Name of the starting station"
          
          - name: start_station_id
            description: "ID of the starting station"
          
          - name: end_station_name
            description: "Name of the ending station"
          
          - name: end_station_id
            description: "ID of the ending station"
          
          - name: end_station_id__v_text
            description: "Text variant of end station ID (dlt metadata)"
          
          - name: start_lat
            description: "Starting latitude coordinate"
          
          - name: start_lng
            description: "Starting longitude coordinate"
          
          - name: end_lat
            description: "Ending latitude coordinate"
          
          - name: end_lng
            description: "Ending longitude coordinate"
          
          - name: member_casual
            description: "Rider membership type (member or casual)"
          
          - name: ride_mins
            description: "Trip duration in minutes (calculated by source system)"
          
          - name: source_month
            description: "Source data month identifier (YYYYMM format)"
          
          - name: _dlt_load_timestamp
            description: "DLT pipeline load timestamp"
          
          - name: _dlt_load_id
            description: "DLT pipeline load batch identifier"
          
          - name: _dlt_id
            description: "DLT unique record identifier"

  - name: raw_weather
    description: "Raw weather data ingested via dlt pipeline from Open-Meteo API"
    database: weather_ingestion
    schema: raw_weather
    tables:
      - name: daily_weather
        description: "Daily weather observations for NYC area"
        columns:
          - name: date
            description: "Date of weather observation (VARCHAR format)"
            tests:
              - unique
              - not_null
          
          - name: tmax
            description: "Maximum temperature in Celsius"
          
          - name: tmin
            description: "Minimum temperature in Celsius"
          
          - name: precip
            description: "Precipitation sum in mm"
          
          - name: wind_max
            description: "Maximum wind speed in km/h"
          
          - name: source_location
            description: "Latitude,longitude coordinates of weather station"
          
          - name: _dlt_load_timestamp
            description: "DLT pipeline load timestamp"
          
          - name: _dlt_load_id
            description: "DLT pipeline load batch identifier"
          
          - name: _dlt_id
            description: "DLT unique record identifier"

